project:
  type: website
  output-dir: docs

website:
  title: " Noelia Senior Project Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/noeliap101

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual 

