project:
  type: website
  output-dir: docs

website:
  title: " noeliap101.github.io Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/

format:
  html:
    theme: cosmo
    css: styles.css



